version: '3.8'

services:
  # user-service
  user-service:
    build:
      context: ./user-service
    container_name: horizon-user-service
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/horizon_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

      JWT_SECRET: some-super-secret-please-change
    depends_on:
      - postgres
      - eureka-server


  # PostgreSQL - Core Ledger & User Data
  postgres:
    image: postgres:14-alpine
    container_name: horizon-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: horizon_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # MongoDB - Budget & Analytics Data
  mongodb:
    image: mongo:latest
    container_name: horizon-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Zookeeper - Cần thiết để Kafka hoạt động
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: horizon-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Kafka - Message Broker chính
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: horizon-kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Cấu hình quan trọng để Kafka hoạt động trong Docker và máy chủ cục bộ
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Eureka Server - Service Discovery
  eureka-server:
    build:
      context: ../services/discovery-service
      dockerfile: ../services/discovery-service/Dockerfile
    container_name: horizon-eureka
    ports:
      - "8761:8761"

volumes:
  postgres_data:
  mongo_data: